-- 202607.018: expand the equity/crypto Yahoo watchlist from the single
-- seeded AAPL row (202606.009) to 19 total by adding 18 new Yahoo Finance v8
-- chart sources: 11 US equities, 2 US ETFs, and 5 crypto pairs. All use
-- kind=LAST and share the AAPL row's title, interval, options, rules, and
-- fetcher_kind verbatim.
--
-- Crypto rows use a distinct CRYPTO_YAHOO_ prefix (not US_YAHOO_) since these
-- are not US-listed markets; the dash in the url ticker (e.g. BTC-USD) is a
-- Yahoo path convention and does not appear in name/base_currency.
--
-- To rotate a stale User-Agent without breaking filename immutability, add a
-- new numbered migration that updates the rows, e.g.:
--   UPDATE rate_sources SET options='{"headers":{"User-Agent":"<new UA>"}}' WHERE name LIKE 'US_YAHOO_LAST_%' OR name LIKE 'CRYPTO_YAHOO_LAST_%';
-- Never edit this file — the filename is immutable once applied to any database.
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_MSFT_USD','Yahoo Finance','MSFT','USD','https://query1.finance.yahoo.com/v8/finance/chart/MSFT','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_GOOGL_USD','Yahoo Finance','GOOGL','USD','https://query1.finance.yahoo.com/v8/finance/chart/GOOGL','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_AMZN_USD','Yahoo Finance','AMZN','USD','https://query1.finance.yahoo.com/v8/finance/chart/AMZN','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_NVDA_USD','Yahoo Finance','NVDA','USD','https://query1.finance.yahoo.com/v8/finance/chart/NVDA','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_META_USD','Yahoo Finance','META','USD','https://query1.finance.yahoo.com/v8/finance/chart/META','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_TSLA_USD','Yahoo Finance','TSLA','USD','https://query1.finance.yahoo.com/v8/finance/chart/TSLA','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_NFLX_USD','Yahoo Finance','NFLX','USD','https://query1.finance.yahoo.com/v8/finance/chart/NFLX','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_AMD_USD','Yahoo Finance','AMD','USD','https://query1.finance.yahoo.com/v8/finance/chart/AMD','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_PLTR_USD','Yahoo Finance','PLTR','USD','https://query1.finance.yahoo.com/v8/finance/chart/PLTR','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_COIN_USD','Yahoo Finance','COIN','USD','https://query1.finance.yahoo.com/v8/finance/chart/COIN','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_AVGO_USD','Yahoo Finance','AVGO','USD','https://query1.finance.yahoo.com/v8/finance/chart/AVGO','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_SPY_USD','Yahoo Finance','SPY','USD','https://query1.finance.yahoo.com/v8/finance/chart/SPY','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('US_YAHOO_LAST_QQQ_USD','Yahoo Finance','QQQ','USD','https://query1.finance.yahoo.com/v8/finance/chart/QQQ','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('CRYPTO_YAHOO_LAST_BTC_USD','Yahoo Finance','BTC','USD','https://query1.finance.yahoo.com/v8/finance/chart/BTC-USD','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('CRYPTO_YAHOO_LAST_ETH_USD','Yahoo Finance','ETH','USD','https://query1.finance.yahoo.com/v8/finance/chart/ETH-USD','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('CRYPTO_YAHOO_LAST_SOL_USD','Yahoo Finance','SOL','USD','https://query1.finance.yahoo.com/v8/finance/chart/SOL-USD','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('CRYPTO_YAHOO_LAST_XRP_USD','Yahoo Finance','XRP','USD','https://query1.finance.yahoo.com/v8/finance/chart/XRP-USD','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
INSERT OR IGNORE INTO rate_sources (name, title, base_currency, quote_currency, url, interval, kind, active, options, rules, rule_metadata, fetcher_kind) VALUES('CRYPTO_YAHOO_LAST_DOGE_USD','Yahoo Finance','DOGE','USD','https://query1.finance.yahoo.com/v8/finance/chart/DOGE-USD','6h','LAST',1,'{"headers":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}}','[{"method":"json","pattern":"chart.result[0].meta.regularMarketPrice"}]','{}','plain');
